# Generated by Django 2.2 on 2021-03-28 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_auto_20210318_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст комментария', validators=[posts.validators.validate_not_empty], verbose_name='Текст комментарий')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, help_text='Напишите комментарий', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='posts.Post', verbose_name='Комметнарий')),
            ],
        ),
    ]
